### ISSUE TITLE
GH API "Not Found" error

### ISSUE THREAD

**Issue by fregante** [RichardLitt/gh-description#4]
```sh
$ gh-description RichardLitt/gh-description 'ponies and unicorns'

{ Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    at /usr/local/lib/node_modules/gh-description/node_modules/octokat/dist/node/request.js:231:19
    at exports.XMLHttpRequest.xhr.onreadystatechange (/usr/local/lib/node_modules/gh-description/node_modules/octokat/dist/node/request.js:45:18)
    at exports.XMLHttpRequest.dispatchEvent (/usr/local/lib/node_modules/gh-description/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/gh-description/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gh-description/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  status: 404,
  json: 
   { message: 'Not Found',
     documentation_url: 'https://developer.github.com/v3' } }
{ Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    at /usr/local/lib/node_modules/gh-description/node_modules/octokat/dist/node/request.js:231:19
    at exports.XMLHttpRequest.xhr.onreadystatechange (/usr/local/lib/node_modules/gh-description/node_modules/octokat/dist/node/request.js:45:18)
    at exports.XMLHttpRequest.dispatchEvent (/usr/local/lib/node_modules/gh-description/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/gh-description/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gh-description/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  status: 404,
  json: 
   { message: 'Not Found',
     documentation_url: 'https://developer.github.com/v3' } }
```

gh-description can get the description well but it fails once I try to set it (after asking for user/pass the first time)

**Comment by RichardLitt** [comment]
I got this too. Check your token in your gh-auth config. See: https://github.com/LinusU/node-application-config

Might be worth getting the new version, too. I changed the env var, fixed the tests.

**Comment by fregante** [comment]
Found the issue: the token didn't have any permissions checked. It should be like this

> <img width="544" alt="screen shot 2017-02-05 at 15 31 39" src="https://cloud.githubusercontent.com/assets/1402241/22624245/6fdd6c2a-eb2a-11e6-8aae-4adb43736916.png">

**Comment by fregante** [comment]
Edit: moved to #7

**Comment by RichardLitt** [comment]
It sends a Not Found for unauthenticated, too. Are you looking for a private repo? Is your current folder a git repo? Have you reset your token?

**Comment by fregante** [comment]
The first issue is gh-description's: the token it generates doesn't have any permissions checked.

The other issue was moved to #7

**Comment by RichardLitt** [comment]
I added information into the README about this in the newest patch. This should be good now.
